# Generated by Django 4.1.1 on 2022-10-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_rename_profile_picture_userinfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
