# Generated by Django 4.1.1 on 2022-10-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
