# Generated by Django 4.1.1 on 2022-10-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_userinfo_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
