# Generated by Django 4.1.1 on 2022-10-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_userinfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
