# Generated by Django 4.1.1 on 2022-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_alter_userinfo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
