# Generated by Django 4.1.1 on 2022-10-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_usermedia_userinfo_usermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='usermedia',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usermedia',
            field=models.ManyToManyField(null=True, to='userProfile.usermedia'),
        ),
    ]
