# Generated by Django 4.1.3 on 2022-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_alter_usermedia_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='gallery',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
