# Generated by Django 4.1.3 on 2022-11-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_usermedia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='usermedia',
        ),
    ]
