# Generated by Django 4.1.3 on 2022-11-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_remove_userinfo_usermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='user',
        ),
    ]
